INSERT INTO `caracteristica` (`id`, `descricao`) VALUES (1, 'Input Monetário');
INSERT INTO `caracteristica` (`id`, `descricao`) VALUES (2, 'Input Data');
INSERT INTO `caracteristica` (`id`, `descricao`) VALUES (3, 'Input Numerico');
INSERT INTO `caracteristica` (`id`, `descricao`) VALUES (4, 'Input Email');
INSERT INTO `caracteristica` (`id`, `descricao`) VALUES (5, 'Input Tel Fixo');
INSERT INTO `caracteristica` (`id`, `descricao`) VALUES (6, 'Input Cel');
INSERT INTO `caracteristica` (`id`, `descricao`) VALUES (7, 'Input CPF');
INSERT INTO `caracteristica` (`id`, `descricao`) VALUES (8, 'Input CNPJ');
INSERT INTO `caracteristica` (`id`, `descricao`) VALUES (9, 'Input CPF/CNPJ');
INSERT INTO `caracteristica` (`id`, `descricao`) VALUES (10, 'Input Text');
